Traceback (most recent call last):
  File "measure_distribution_parameters.py", line 85, in <module>
    params, _  = curve_fit(dist.pdf, binc, N_obs, p0 = dist.p0)
  File "/cosma/home/dp004/dc-wilk2/python_venv/lib64/python3.6/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 600.
srun: error: m6085: task 0: Exited with exit code 1
/cosma7/data/dp004/dc-wilk2/flare/projects/flares_sfzh/analysis/sfh/util.py:52: RuntimeWarning: invalid value encountered in true_divide
  return pdf_/((x[1]-x[0])*np.sum(pdf_))
/cosma/home/dp004/dc-wilk2/python_venv/lib64/python3.6/site-packages/scipy/optimize/minpack.py:829: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)
Traceback (most recent call last):
  File "measure_distribution_parameters.py", line 85, in <module>
    params, _  = curve_fit(dist.pdf, binc, N_obs, p0 = dist.p0)
  File "/cosma/home/dp004/dc-wilk2/python_venv/lib64/python3.6/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 600.
srun: error: m6085: task 0: Exited with exit code 1
